########daftar192.168.1.2
POST http://localhost:8080/ HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
 
{   
    "teee": "teee" 
}


########daftar192.168.1.2
//POST http://localhost/belajar_api_php/create_user.php
POST http://localhost:8080/register
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
 
{
   "kat":"customer" ,
   "name":"zul ghgh" ,
   "email":"H_HAAA@jggggwg.vvt" ,
   "password":"password" ,
   "phone_number":82547814116,
   "phone_id":"+62"  ,
   "gcm":"gcm"  
 }

########pin
//POST http://localhost:8080/validasireset  HTTP/1.1
POST http://192.168.1.44:8080/validasiregister  HTTP/1.1
Content-Type: application/json 

{    
    "typeuser": "customer", 
    "phone_id": "+62", 
    "phone_number": 82256330257
}
########resetpassword
POST http://localhost:8080/resetpassword  HTTP/1.1 
Content-Type: application/json 

{    

    "typeuser": "customer", 
    "phone_id": "+62", 
    "phone_number": 82256330257,
    "password": "customer",
    "pin": 230131
}

########login
# @name myRequest
POST http://192.168.1.44:8080/login HTTP/1.1
Content-Type: application/json 
  
{
    "usertype":"customer",
   // "email": "a@customer.com",
    "phone_id": "+62", 
    "phone_number": 82256330257,
    "password": "password",
    "gcm":"eeee"
    //"refresh":"chSaisNXME0:APA91bG2DY1bAi28mBEfDVcNyAjpCV6vYdCOfVKytyxO2af9-t65plPOAi2D36PKAVx9XCNFRWzVSo4AxYSyi1pO6db0WRpkm809M5zeuqgBi1RSCHIjFDOKyADLXQj-wSPt9XIIp67V"
}

######## promotion######## promotion
GET http://192.168.1.44:8080/getalltopup?page=1&limit=10 HTTP/1.1 
Content-Type: application/json 
Authorization: "{{myRequest.response.body.token}}"

{

}

########me
POST http://localhost/webku/ojek_online/gcm_ojek/public/api/v1/me HTTP/1.1
Content-Type: application/json
Authorization:  "Bearer {{myRequest.response.body.access_token}}"

{
   // "phone_number": "44253354311",
   // "password": "password"
}


########logout
POST http://localhost/webku/ojek_online/gcm_ojek/public/api/v1/logout HTTP/1.1
Content-Type: application/json
Authorization:  "Bearer {{myRequest.response.body.access_token}}"

########refresh
POST http://localhost/webku/ojek_online/gcm_ojek/public/api/v1/refresh HTTP/1.1
Content-Type: application/json
Authorization:  "Bearer {{myRequest.response.body.access_token}}"


########users
GET http://localhost/webku/ojek_online/gcm_ojek/public/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization:  "Bearer {{myRequest.response.body.access_token}}"


########refresh
POST http://localhost/webku/ojek_online/gcm_ojek/public/api/v1/refresh HTTP/1.1
Content-Type: application/json
Authorization:  "Bearer {{myRequest.response.body.access_token}}"


########gojekprice
POST http://localhost/webku/ojek_online/gcm_ojek/public/api/v1/gojekprice HTTP/1.1
Content-Type: application/json
Authorization:  "Bearer {{myRequest.response.body.access_token}}"
 
{
    "prov_1": "SulawesiBarat91353",
    "prov_2": "SulawesiBarat91353",
    "origin_lat": "-3.4798748637270114",
    "origin_long": "119.14480838924646",
    "destination_lat": "-3.4779221326351752",
    "destination_long": "119.14588630199432",
    "category_driver": "motorcycle",
    "pay_categories": "cash",
    "jemput_judul": "jemput_judul",
    "jemput_alamat": "jemput_alamat",
    "jemput_ket": "jemput_ket",
    "tujuan_judul": "tujuan_judul",
    "tujuan_alamat": "tujuan_alamat"
}


########gojekorder
POST http://localhost/webku/ojek_online/gcm_ojek/public/api/v1/gojekorder HTTP/1.1
Content-Type: application/json
Authorization:  "Bearer {{myRequest.response.body.access_token}}"
 
{
    "order":"70efdf2ec9b086079795c442636b55fb"
}

######## inbox
GET http://localhost/webku/ojek_online/gcm_ojek/public/api/v1/inbox/2 HTTP/1.1
Content-Type: application/json
Authorization:  "Bearer {{myRequest.response.body.access_token}}"
 

